# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'jnsup_danger.py parameters'
        # Default value if no value is explicitly provided
        default: '-h'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PRISMA_ACCESS_KEY_ID: ${{ secrets.PRISMA_ACCESS_KEY_ID }}
      PRISMA_SECRET_KEY: ${{ secrets.PRISMA_SECRET_KEY }}
      PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: checkout repo code
      uses: actions/checkout@v4
    # - name: Run jnsup.py
    #   run: |
    #     python3 -V
    #     env | grep "PRISMA_*" | wc -l
    #     ls -la
    #     python3 -m pip install -U pip
    #     python3 -m pip install -r requirements.txt
    #     python3 jnsup_danger.py ${{ inputs.name }}
    - name: Check for jq
      run: |
        token=$(curl -L -X POST $PRISMA_API_URL'/login' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json; charset=UTF-8' --data-raw '{ "password": "'$PRISMA_SECRET_KEY'", "username": "'$PRISMA_ACCESS_KEY_ID'"}' | jq -r '.token')
        echo $token | wc -c
        curl $PRISMA_API_URL'/policy?policy.type=config&policy.subtype=build' -H 'Accept: application/json; charset=UTF-8' -H 'x-redlock-auth: '${token} | jq '.[] | .name, .createdBy'
